# Generated by Django 4.1 on 2022-09-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_player_last_login_remove_player_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
