# Generated by Django 4.1 on 2022-09-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_player_position_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='positions', to='base.position'),
        ),
    ]
